[package]
name = "rubikscube"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
memmap2 = "0.9.9"
num-format = "0.4.4"
once_cell = "1.21.3"
rand = "0.9.2"
rayon = "1.11.0"

[dev-dependencies]
criterion = "0.7"
itertools = "0.14"

[[bench]]
name = "math_bench"
harness = false

[[bench]]
name = "twist_bench"
harness = false

[profile.profiling]
inherits = "release"
debug = true
